services:
  - type: web
    name: sachack26-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    buildFilter:
      paths:
        - main.py
        - requirements.txt
        - dummy_data/**
        - Dockerfile
